In [1]:
import numpy as np

#creating array in numpy

In [13]:
myarr=np.array([1,2,34,])

In [14]:
myarr

array([ 1,  2, 34])

# agar array bada ho to khud manage krega

In [15]:
myarr=np.array([1,2,3,45],np.int64)

In [16]:
myarr

array([ 1,  2,  3, 45], dtype=int64)

In [17]:
myarr=np.array([[1,2,3,45]],np.int64)

In [18]:
myarr[0,2]

3

In [19]:
myarr=np.array([1,2,3,45],np.int64)


In [20]:
myarr[3]

45

In [21]:
myarr.shape

(4,)

In [22]:
myarr.dtype

dtype('int64')

In [23]:
myarr[0,1]=60

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [24]:
myarr=np.array([1,2,3,45],np.int64)

In [25]:
myarr

array([ 1,  2,  3, 45], dtype=int64)

In [26]:
myarr[0,2]=60

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [27]:
myarr=np.array([[1,2,3,45]],np.int64)

In [28]:
myarr

array([[ 1,  2,  3, 45]], dtype=int64)

In [29]:
myarr[0,2]=60

In [30]:
myarr

array([[ 1,  2, 60, 45]], dtype=int64)

In [31]:
myarr=np.array([1,2,3,45],np.int64)

In [32]:
myarr

array([ 1,  2,  3, 45], dtype=int64)

In [33]:
myarr[3]=60

In [34]:
myarr

array([ 1,  2,  3, 60], dtype=int64)

# array creation method in numpy

# 1) conversion from other source python(ex:- str,list,tuple)

In [35]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
listarray.dtype

dtype('int32')

In [38]:
listarray.shape

(3, 3)

In [39]:
listarray.size

9

# 2) intrinsic numpy array creation objects(ex:- arange,ones,zeros etc.)

In [40]:
zeros=np.zeros((2,5))

In [41]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
zeros=np.zeros((2,5))

In [43]:
zeros.dtype

dtype('float64')

In [44]:
zeros.shape

(2, 5)

In [45]:
rng=np.arange(10)

In [46]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
lspace=np.linspace(1,3,4)

In [48]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [49]:
lspace=np.linspace(1,5,8)

In [50]:
lspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [51]:
emp=np.empty((4,6))

In [52]:
emp

array([[1.48729778e-312, 1.48646480e-312, 1.69121096e-306,
        1.78020169e-306, 4.45058910e-308, 1.78021119e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37960147e-306,
        1.33511562e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.37961913e-306, 7.56599128e-307, 1.11260144e-306,
        6.89812281e-307, 2.22522596e-306, 3.91786943e-317]])

In [53]:
import numpy as np

In [54]:
lspace=np.linspace(1,3,4)

In [55]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [56]:
emp_like=np.empty_like(lspace)

In [57]:
emp_like

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [58]:
ide=np.identity(12)

In [59]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
ide.shape

(12, 12)

In [61]:
arr=np.arange(99)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [64]:
arr=arr.ravel()

# numpy axis

In [65]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [66]:
ar=np.array(x)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
ar.sum(axis=0)

array([12,  8,  9])

In [69]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [70]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [71]:
ar.ndin

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [72]:
ar.size

9

In [73]:
ar.nbytes

36

In [74]:
one=np.array([1,2,3,4,5])

In [75]:
one.argmax()

4

In [76]:
one.argmin()

0

In [77]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar.argmin()

8

In [80]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [81]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [82]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [83]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [84]:
ar2=np.array([[1,2,3],[3,5,6],[3,5,2]])

In [85]:
ar2

array([[1, 2, 3],
       [3, 5, 6],
       [3, 5, 2]])

In [86]:
ar+ar2

array([[ 2,  4,  6],
       [ 7, 10, 12],
       [10,  6,  2]])

In [87]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [88]:
ar.sum()

29

In [89]:
ar.max()

7

In [90]:
ar.min()

0

In [91]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [92]:
type(np.where(ar>4))

tuple

In [93]:
np.count_nonzero(ar)

8

In [94]:
np.count_zero(ar)

AttributeError: module 'numpy' has no attribute 'count_zero'

In [95]:
import sys

In [96]:
py_r=[0,4,5,5,6]

In [97]:
np_r=np.array(py_r)

In [100]:
sys.getsizeof(1)*len(py-r)

NameError: name 'py' is not defined